#ifndef __SAMPLE_LOG_H_
#define __SAMPLE_LOG_H_

#include "string.h"
#include "PmLogLib.h"

PmLogContext GetPmLogContext();

#define PMLOG_DEBUG(msgId, ...)      PmLogMsg(GetPmLogContext(), Debug, msgId, 0, __VA_ARGS__)
#define PMLOG_INFO(msgId, ...)       PmLogMsg(GetPmLogContext(), Info, msgId, 0, __VA_ARGS__)

#define MSGID_LUNA_SEND_FAILED					"LUNA_SEND_FAILED"
#define MSGID_LUNA_CREATE_JSON_FAILED			"LUNA_CREATE_JSON_FAILED"
#define MSGID_UNEXPECTED_EXCEPTION				"UNEXPECTED_EXCEPTION"
#define MSGID_LS2_DISCONNECTED					"LS2_DISCONNECTED"
#define MSGID_LS2_NO_HANDLER					"LS2_NO_HANDLER"
#define MSGID_LS2_NOT_SUBSCRIBED				"LS2_NOT_SUBSCRIBED"
#define MSGID_LS2_SUBSCRIBE_FAILED				"LS2_SUBSCRIBE_FAILED"
#define MSGID_LS2_CALL_PARSE_FAILED				"LS2_CALL_PARSE_FAILED"
#define MSGID_LS2_INVALID_SUBSCRIPTION_RESPONSE	"LS2_INVALID_SUBSCRIPTION"
#define MSGID_LS2_INVALID_RESPONSE				"LS2_INVALID_RESPONSE"
#define MSGID_LS2_DOUBLE_DEFER					"LS2_DOUBLE_DEFER"
#define MSGID_LS2_CALL_RESPONSE_INVALID_HANDLE	"LS2_CALL_RESPONSE_INVALID"
#define MSGID_LS2_HUB_ERROR						"LS2_HUB_ERROR"
#define MSGID_LS2_RESPONSE_PARSE_FAILED			"LS2_RESPONSE_PARSE_FAILED"
#define MSGID_LS2_FAILED_TO_PARSE_PARAMETERS	"LS2_FAIL_TO_PARSE_PARAMETERS"
#define MSGID_LS2_REGISTERSERVERSTATUS_FAILED	"LS2_REGSERVERSTATUS_FAILED"
#define MSGID_MALFORMED_JSON					"MALFORMED_JSON"
#define MSGID_GET_SYSTEM_SETTINGS_ERROR			"GET_SYSTEM_SETTINGS_ERROR"
#define MSGID_SCHEMA_VALIDATION					"SCHEMA_VALIDATION"
#define MSGID_MULTIPLE_LUNA_REPLIES				"MULTIPLE_LUNA_REPLIES"
#define MSGID_JSON_PARSE_ERROR					"JSON_PARSE_ERROR"
#define MSGID_LS2_RECEIVED_INFO					"LS2_RECEIVED"
#define MSGID_LS2_SEND_INFO						"LS2_SEND"
#define MSGID_LS2_SUBSCRIBED_INFO				"LS2_SUBSCRIBED"
#define MSGID_FACTORY_SERVICE_INFO				"FACTORY_MAIN"
#define MSGID_NOP_TIMER_INFO					"NOP_TIMER"
#define MSGID_NOP_EXCEPTION_ERROR				"NOP_ERROR"
#define MSGID_CTRL_JOB_TIMER_INFO				"JOB_TIMER"
#define MSGID_CTRL_EPL_INFO						"EPL_CTRL"
#define MSGID_TERMINATING 						"TERMINATING"
#define MSGID_SIGNAL_HANDLER_ERROR 				"SIGNAL_HANDLER_ERROR"
#define MSGID_FACTORY_ADJ_CMD_INFO				"ADJUST_CMD"

#endif
